/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hojasverdes;

import dominio.camion;
import dominio.cliente;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fralkayg
 */
public class mantenedorCliente extends javax.swing.JFrame {
    
    DefaultTableModel modelo = new DefaultTableModel();
    conectar cnx = new conectar();
    Connection reg= cnx.conexion();
    //private TableRowSorter trsfiltro;
    int columna=0;
    int sw = 0;
    String sql;

    /**
     * Creates new form mantenedorCliente
     */
    public mantenedorCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Mantenedor Cliente");
        tbl_cliente.setAutoCreateRowSorter(true);
        //ingresa las columnas de tu tabla productos
        modelo.addColumn("RUT");
        modelo.addColumn("Nombre");
        modelo.addColumn("Direccion");
        modelo.addColumn("Giro");
        modelo.addColumn("Telefono");
        modelo.addColumn("Contacto");
        modelo.addColumn("Razon social");
        tbl_cliente.setModel(modelo);
        btn_aceptar.setVisible(false);
        btn_cancelar.setVisible(false);
        mostrardatostabla("");
    }
    
    void mostrardatostabla(String valor){    
        String []datos=new String[7];
        int cod;
        String sql="";
        if(valor.equals("")){
            sql="SELECT * FROM cliente";
        }else{
            sql="SELECT * FROM cliente WHERE rut_cliente='"+valor+"'";
        }
        try {
            Statement st = reg.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                //aqui se agregan los campos
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                modelo.addRow(datos);
            }
            tbl_cliente.setModel(modelo);
            
        } catch (SQLException ex) {
            Logger.getLogger(producto.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }
    
    public void limpiartabla(){
       // tabla.setModel(new DefaultTableModel());
        for (int i = 0; i < tbl_cliente.getRowCount(); i++) {
           modelo.removeRow(i);
           i-=1;
       }
    }    
    
    static public boolean validar(String rut) {
        boolean validacion = false;
        try {
            rut = rut.toUpperCase();
            int rutAux = Integer.parseInt(rut.substring(0, rut.length() - 1));

            char dv = rut.charAt(rut.length() - 1);

            int m = 0, s = 1;
            for (; rutAux != 0; rutAux /= 10) {
                s = (s + rutAux % 10 * (9 - m++ % 6)) % 11;
            }
            if (dv == (char) (s != 0 ? s + 47 : 75)) {
                validacion = true;
            }

        } catch (java.lang.NumberFormatException e) {
        } catch (Exception e) {
        }
        return validacion;
    }    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_rutCliente = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_razonSocial = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_giro = new javax.swing.JTextField();
        txt_contacto = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_aceptar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_cliente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Rut cliente:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 16, -1, -1));

        jLabel2.setText("Direccion:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 54, -1, -1));

        jLabel3.setText("Telefono:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 92, -1, -1));

        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 16, -1, -1));

        jLabel5.setText("Giro:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 54, -1, -1));

        jLabel6.setText("Contacto:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 92, -1, -1));

        jLabel7.setText("Razon social:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 133, -1, -1));

        txt_rutCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_rutClienteFocusLost(evt);
            }
        });
        txt_rutCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rutClienteKeyTyped(evt);
            }
        });
        jPanel1.add(txt_rutCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 13, 179, -1));

        txt_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_direccionKeyTyped(evt);
            }
        });
        jPanel1.add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 51, 179, -1));

        txt_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefonoKeyTyped(evt);
            }
        });
        jPanel1.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 89, 179, -1));

        txt_razonSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_razonSocialKeyTyped(evt);
            }
        });
        jPanel1.add(txt_razonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 130, 179, -1));

        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 13, 229, -1));

        txt_giro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_giroKeyTyped(evt);
            }
        });
        jPanel1.add(txt_giro, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 51, 229, -1));

        txt_contacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_contactoKeyTyped(evt);
            }
        });
        jPanel1.add(txt_contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 89, 229, -1));

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add.png"))); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, -1, 29));

        btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/update.png"))); // NOI18N
        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete.png"))); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        btn_aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/OK-20.png"))); // NOI18N
        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete.png"))); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        tbl_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "RUT", "Nombre", "Direccion", "Giro", "Telefono", "Contacto", "Razon social"
            }
        ));
        jScrollPane1.setViewportView(tbl_cliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        if (txt_rutCliente.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Debe ingresar rut cliente");
        }else{
            if (txt_nombre.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Debe ingresar nombre cliente");
            }else{
                if (txt_direccion.getText().equals("")){
                    JOptionPane.showMessageDialog(null,"Debe ingresar direccion cliente");
                }else{
                    if (txt_giro.getText().equals("")){
                        JOptionPane.showMessageDialog(null,"Debe ingresar giro");
                    }else{
                        if (txt_telefono.getText().equals("")){
                            JOptionPane.showMessageDialog(null,"Debe ingresar telefono cliente");
                        }else{
                            if (txt_contacto.getText().equals("")){
                                txt_contacto.setText(" ");
                            }
                            if (txt_razonSocial.getText().equals("")){
                                txt_razonSocial.setText("");
                            }
                            cliente dto = new cliente();
                            dto.setRut_cliente(txt_rutCliente.getText());
                            dto.setNombre(txt_nombre.getText());
                            dto.setDireccion(txt_direccion.getText());
                            dto.setGiro(txt_giro.getText());
                            dto.setTelefono(Integer.parseInt(txt_telefono.getText()));
                            //JOptionPane.showMessageDialog(null, dto.getTelefono());
                            dto.setContacto(txt_contacto.getText());
                            dto.setRazon_social(txt_razonSocial.getText());
                            sql= "INSERT INTO cliente (rut_cliente, nombre, direccion, giro, telefono, contacto, razon_social)VALUES (?,?,?,?,?,?,?)";
                            try {
                                PreparedStatement pst=reg.prepareStatement(sql);
                                pst.setString(1, dto.getRut_cliente());
                                pst.setString(2, dto.getNombre());
                                pst.setString(3, dto.getDireccion());
                                pst.setString(4, dto.getGiro());
                                pst.setInt(5, dto.getTelefono());
                                pst.setString(6, dto.getContacto());
                                pst.setString(7, dto.getRazon_social());
                                int n = pst.executeUpdate();
                                if (n>0){
                                    JOptionPane.showMessageDialog(null,"Cliente registrado satisfactoriamente.");
                                }                
                            }catch (SQLException ex) {
                                JOptionPane.showMessageDialog(null,"Error al agregar, cliente duplicada.");
                                //sw = 1;
                            }       
                            txt_rutCliente.setText("");
                            txt_nombre.setText("");
                            txt_direccion.setText("");
                            txt_giro.setText("");
                            txt_telefono.setText("");
                            txt_contacto.setText("");
                            txt_razonSocial.setText("");
                            limpiartabla();
                            mostrardatostabla(""); 
                        }
                    }
                }
            }
        }
        
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        int fila=tbl_cliente.getSelectedRow();
        if (fila>=0){
            txt_rutCliente.setText(tbl_cliente.getValueAt(fila, 0).toString());
            txt_nombre.setText(tbl_cliente.getValueAt(fila, 1).toString());
            txt_direccion.setText(tbl_cliente.getValueAt(fila, 2).toString());
            txt_giro.setText(tbl_cliente.getValueAt(fila, 3).toString());
            txt_telefono.setText(tbl_cliente.getValueAt(fila, 4).toString());
            txt_contacto.setText(tbl_cliente.getValueAt(fila, 5).toString());
            txt_razonSocial.setText(tbl_cliente.getValueAt(fila, 6).toString());
            txt_rutCliente.setEditable(false);
            txt_rutCliente.setEnabled(false);
            btn_agregar.setVisible(false);
            btn_modificar.setVisible(false);
            btn_eliminar.setVisible(false);
            btn_aceptar.setVisible(true);
            btn_cancelar.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"No selecciono fila");
        }
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        if (txt_rutCliente.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Debe ingresar rut cliente");
        }else{
            if (txt_nombre.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Debe ingresar nombre cliente");
            }else{
                if (txt_direccion.getText().equals("")){
                    JOptionPane.showMessageDialog(null,"Debe ingresar direccion cliente");
                }else{
                    if (txt_giro.getText().equals("")){
                        JOptionPane.showMessageDialog(null,"Debe ingresar giro");
                    }else{
                        if (txt_telefono.getText().equals("")){
                            JOptionPane.showMessageDialog(null,"Debe ingresar telefono cliente");
                        }else{
                            if (txt_contacto.getText().equals("")){
                                txt_contacto.setText(" ");
                            }
                            if (txt_razonSocial.getText().equals("")){
                                txt_razonSocial.setText("");
                            }
                            sql="UPDATE cliente SET nombre='"+txt_nombre.getText()+"',direccion='"+txt_direccion.getText()+"', giro='"+txt_giro.getText()+"', telefono="+Integer.parseInt(txt_telefono.getText())+", contacto='"+txt_contacto.getText()+"', razon_social='"+txt_razonSocial.getText()+"'  WHERE rut_cliente="+txt_rutCliente.getText()+"";
                            try {
                                PreparedStatement pst = reg.prepareStatement(sql);
                                pst.executeUpdate();
                                limpiartabla();
                                mostrardatostabla("");
                            } catch (Exception e) {
                                System.out.println(e.getMessage());
                                JOptionPane.showMessageDialog(null,e.getMessage());
                            }
                            btn_aceptar.setVisible(false);
                            btn_cancelar.setVisible(false);
                            btn_eliminar.setVisible(true);
                            btn_modificar.setVisible(true);
                            btn_agregar.setVisible(true);
                            txt_rutCliente.setEnabled(true);
                            txt_rutCliente.setEditable(true);
                            txt_rutCliente.requestFocus();
                            txt_rutCliente.setText("");
                            txt_nombre.setText("");
                            txt_direccion.setText("");
                            txt_giro.setText("");
                            txt_telefono.setText("");
                            txt_contacto.setText("");
                            txt_razonSocial.setText("");
                            limpiartabla();
                            mostrardatostabla("");
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        btn_aceptar.setVisible(false);
        btn_cancelar.setVisible(false);
        btn_eliminar.setVisible(true);
        btn_modificar.setVisible(true);
        btn_agregar.setVisible(true);
        txt_rutCliente.setEnabled(true);
        txt_rutCliente.setEditable(true);
        txt_rutCliente.requestFocus();
        txt_rutCliente.setText("");
        txt_nombre.setText("");
        txt_direccion.setText("");
        txt_giro.setText("");
        txt_telefono.setText("");
        txt_contacto.setText("");
        txt_razonSocial.setText("");
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        int fila = tbl_cliente.getSelectedRow();
        if (fila >= 0){   
            if(JOptionPane.showConfirmDialog(null, new Object[]{"Seguro que desea Eliminar fila seleccionada?"},"Eliminar",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.YES_OPTION){
            //qui se pone lo que hara si le das aceptar
                fila=tbl_cliente.getSelectedRow();
                txt_rutCliente.setText(tbl_cliente.getValueAt(fila, 0).toString());
                try {
                    PreparedStatement pst = reg.prepareStatement("DELETE FROM cliente WHERE rut_cliente="+Integer.parseInt(txt_rutCliente.getText())+"");
                    pst.executeUpdate();
                    limpiartabla();
                    mostrardatostabla("");
                    txt_rutCliente.setText("");
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
            }else{
            //aqui se pone lo que hara si le das cancelar
            }
        }else{
            JOptionPane.showMessageDialog(null,"Debe seleccionar una fila antes de eliminar.");
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void txt_rutClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rutClienteKeyTyped
        int limite = 9;
        if (txt_rutCliente.getText().length() == limite) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_rutClienteKeyTyped

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        int limite = 30;
        if (txt_nombre.getText().length() == limite) {
            evt.consume();
        }

        char t = evt.getKeyChar();
        if (Character.isDigit(t)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }           
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void txt_direccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_direccionKeyTyped
        int limite = 30;
        if (txt_direccion.getText().length() == limite) {
            evt.consume();
        }
        
    }//GEN-LAST:event_txt_direccionKeyTyped

    private void txt_giroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_giroKeyTyped
        int limite = 30;
        if (txt_giro.getText().length() == limite) {
            evt.consume();
        }
        char t = evt.getKeyChar();
        if (Character.isDigit(t)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }   

    }//GEN-LAST:event_txt_giroKeyTyped

    private void txt_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonoKeyTyped
        int limite = 8;
        if (txt_telefono.getText().length() == limite) {
            evt.consume();
        }
        char t = evt.getKeyChar();
        if (Character.isLetter(t)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
        }
        
    }//GEN-LAST:event_txt_telefonoKeyTyped

    private void txt_contactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contactoKeyTyped
        int limite = 30;
        if (txt_contacto.getText().length() == limite) {
            evt.consume();
        }
        char t = evt.getKeyChar();
        if (Character.isDigit(t)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }           
    }//GEN-LAST:event_txt_contactoKeyTyped

    private void txt_razonSocialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_razonSocialKeyTyped
        int limite = 30;
        if (txt_razonSocial.getText().length() == limite) {
            evt.consume();
        }
        char t = evt.getKeyChar();
        if (Character.isDigit(t)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }           
    }//GEN-LAST:event_txt_razonSocialKeyTyped

    private void txt_rutClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_rutClienteFocusLost
        if (txt_rutCliente.getText().equals("")){
            
        }else{
            
        
        if (!validar(txt_rutCliente.getText())) {
                JOptionPane.showMessageDialog(null, "Error RUT invalido", "Error", JOptionPane.ERROR_MESSAGE);
                txt_rutCliente.setText("");
                txt_rutCliente.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_rutClienteFocusLost

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        cnx.cerrar();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mantenedorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mantenedorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mantenedorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mantenedorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mantenedorCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_cliente;
    private javax.swing.JTextField txt_contacto;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_giro;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_razonSocial;
    private javax.swing.JTextField txt_rutCliente;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
